# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - MAKEFLAGS="-j 2"

# Linux:
addons:
  apt:
    packages:
      - libmagick++-dev
      - libssh2-1-dev

# OS X (R release only)
matrix:
  include:
    - r: oldrel
    - r: release
      env: DEPLOY_PAGES=true
      r_github_packages:
        - krlmlr/pkgdown@develop
    - r: devel
    - os: osx
      osx_image: xcode7.2
      r: release
      latex: false

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - scripts/deploy-pages.sh
  - R -e 'covr::codecov()'; fi

# Custom parts:

r_github_packages:
  - krlmlr/travis@develop

r_packages:
  - covr

