# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - MAKEFLAGS="-j 2"

r:
  - oldrel
  - release
  - devel

# Linux:
addons:
  apt:
    packages:
      - libmagick++-dev

# OS X (R release only)
matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      r: release
      latex: false

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - krlmlr/travis@develop
  - krlmlr/pkgdown@develop

r_packages:
  - covr

after_success:
  - R -e "travis::deploy(tasks = c('travis::task_install_ssh_keys()'))"
  - scripts/deploy-pages.sh
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
