# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: no
cache: packages

warnings_are_errors: true
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - MAKEFLAGS="-j 2"

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - libmagick++-dev

r_github_packages:
  - krlmlr/travis@develop
  - hadley/pkgdown

after_success:
  - R -e "travis::deploy(tasks = c('travis::task_install_ssh_keys()'))"
  - scripts/deploy-pages.sh
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
