# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: no
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - MAKEFLAGS="-j 2"

r_github_packages:
  - krlmlr/travis@develop
  - hadley/pkgdown

after_success:
  - R -e "travis::deploy(tasks = c('travis::task_install_ssh_keys()'))"
  - scripts/deploy-pages.sh
